apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-django
spec:
  selector:
    matchLabels:
      app: mysql-django
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-django
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: mysql-django
        #namespace: coba-namespace
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 3306
      restartPolicy: Always
     
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-django
  #namespace: coba-namespace
  labels:
    app: mysql-django
spec:
  type: NodePort
  ports:
  - port: 3306
    nodePort: 30309
  selector:
    app: mysql-django
